kind: Deployment
apiVersion: apps/v1
metadata:
  name: allotr-react-frontend
  namespace: openfaas-fn
  labels:
    app: allotr-react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: allotr-react-frontend
  template:
    metadata:
      labels:
        app: allotr-react-frontend
    spec:
      containers:
        - name: allotr-react-frontend
          image: rafaelpernil/allotr-react-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name:  VITE_WS_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  VITE_WS_API_ENDPOINT
            - name:  VITE_WEBPUSH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  VITE_WEBPUSH_ENDPOINT
            - name:  VITE_HTTPS_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  VITE_HTTPS_API_ENDPOINT
            - name:  VITE_GOOGLE_LOGIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  VITE_GOOGLE_LOGIN_ENDPOINT
            - name:  VITE_GOOGLE_LOGOUT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  VITE_GOOGLE_LOGOUT_ENDPOINT
            - name:  VITE_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  VITE_REDIRECT_URL
            - name:  HTTPS
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  HTTPS
            - name:  SSL_CRT_FILE
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  SSL_CRT_FILE
            - name:  SSL_KEY_FILE
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  SSL_KEY_FILE
            - name:  PORT
              valueFrom:
                secretKeyRef:
                  name:  allotr-react-frontend-secret
                  key:  PORT
      restartPolicy: Always