kind: Deployment
apiVersion: apps/v1
metadata:
  name: allotr-react-frontend
  namespace: openfaas-fn
  labels:
    app: allotr-react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: allotr-react-frontend
  template:
    metadata:
      labels:
        app: allotr-react-frontend
    spec:
      containers:
        - name: allotr-react-frontend
          image: rafaelpernil/allotr-react-frontend
          serviceAccountName: custom-account
          automountServiceAccountToken: false
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 1Gi
              cpu: "500m"
            requests:
              memory: 1Gi
              cpu: "250m"
      restartPolicy: Always
